# Generated by Django 2.2.28 on 2022-08-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20220819_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(max_length=50)),
                ('frage', models.CharField(max_length=200)),
                ('antwort1', models.CharField(max_length=50)),
                ('antwort2', models.CharField(max_length=50)),
                ('antwort3', models.CharField(max_length=50)),
                ('antwort4', models.CharField(max_length=50)),
                ('richtig', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Quiz_Black',
        ),
        migrations.DeleteModel(
            name='Quiz_Green',
        ),
        migrations.DeleteModel(
            name='Quiz_Red',
        ),
    ]
