# Generated by Django 2.2.28 on 2022-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20220830_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='antwort1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='antwort2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='antwort3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='antwort4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='richtig',
            field=models.CharField(max_length=100),
        ),
    ]
